/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.Admin;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class AdminRegister extends javax.swing.JPanel {

    private MouseListener eventLogin;

    public AdminRegister() {
        initComponents();
        init();
    }
    private void init(){
        Font txtFont = new java.awt.Font("Times New Roman", 1, 15);
        Font btnFont = new java.awt.Font("Times New Roman", Font.BOLD, 16);
        
        txtEmail.setFont(txtFont);
        txtPass.setFont(txtFont);
        txtName.setFont(txtFont);
        txtPassConfirm.setFont(txtFont);

        btnSubmit.setFont(btnFont);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new uitravel.Components.RoundedPanel();
        txtEmail = new uitravel.Components.TextField();
        txtName = new uitravel.Components.TextField();
        txtPass = new uitravel.Components.PasswordField();
        txtPassConfirm = new uitravel.Components.PasswordField();
        btnSubmit = new uitravel.Components.MyButton();
        jLabel2 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setBorderColor(new java.awt.Color(204, 204, 204));
        roundedPanel1.setWithBorder(true);

        txtEmail.setLabelText("Địa chỉ Email:");

        txtName.setLabelText("Họ và tên:");

        txtPass.setLabelText("Mật khẩu:");
        txtPass.setShowAndHide(true);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        txtPassConfirm.setLabelText("Xác nhận mật khẩu:");
        txtPassConfirm.setShowAndHide(true);
        txtPassConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfirmActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(255, 102, 0));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Đăng ký");
        btnSubmit.setBorderColor(new java.awt.Color(255, 102, 0));
        btnSubmit.setBorderPainted(false);
        btnSubmit.setColor(new java.awt.Color(255, 102, 0));
        btnSubmit.setColorClick(new java.awt.Color(255, 102, 0));
        btnSubmit.setColorOver(new java.awt.Color(255, 0, 0));
        btnSubmit.setRadius(30);
        btnSubmit.setTransparent(false);
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
        });
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Đăng ký");

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(76, 100, 255));
        lblLogin.setText("Đăng nhập tại đây");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Đã có tài khoản?");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogin))
                            .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblLogin))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        add(roundedPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        lblLogin.setForeground(new Color(0,0,150));

    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setForeground(new Color(76,100,255));
    }//GEN-LAST:event_lblLoginMouseExited

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfirmActionPerformed

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
        eventLogin.mousePressed(evt);
    }//GEN-LAST:event_lblLoginMousePressed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
       
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed
          if("".equals(txtEmail.getText())){
                 JOptionPane.showMessageDialog(null,
                        "Không được để Email trống!",
                        "Thông báo!",
                        
                        JOptionPane.INFORMATION_MESSAGE);
            }
           else if("".equals(txtName.getText())){
                 JOptionPane.showMessageDialog(null,
                        "Không được để tên trống!",
                        "Thông báo!",
                        
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else if("".equals(txtPass.getText())){
                 JOptionPane.showMessageDialog(null,
                        "Không được để mật khẩu trống!",
                        "Thông báo!",
                        
                        JOptionPane.INFORMATION_MESSAGE);
            }
             else if("".equals(txtPassConfirm.getText())){
                 JOptionPane.showMessageDialog(null,
                        "Vui lòng xác nhận mật khẩu!",
                        "Thông báo!",
                        
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else if(!txtPassConfirm.getText().equals(txtPass.getText())){
                 JOptionPane.showMessageDialog(null,
                        "Mật khẩu xác nhận không trùng khớp!",
                        "Thông báo!",
                        
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,
                      "Vui lòng đăng nhập lại!",
                      "Thông báo!",

                      JOptionPane.INFORMATION_MESSAGE);
                eventLogin.mousePressed(evt);
            }  
    }//GEN-LAST:event_btnSubmitMousePressed
  
    public void addLogin(MouseListener event) {
        this.eventLogin = event;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.Components.MyButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblLogin;
    private uitravel.Components.RoundedPanel roundedPanel1;
    private uitravel.Components.TextField txtEmail;
    private uitravel.Components.TextField txtName;
    private uitravel.Components.PasswordField txtPass;
    private uitravel.Components.PasswordField txtPassConfirm;
    // End of variables declaration//GEN-END:variables
}
