/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.Components.MainUI;

import java.awt.*;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.RenderingHints;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import uitravel.LoginMain;
import uitravel.UserInfo;

/**
 *
 * @author ACER
 */
public class LoggedHeader extends javax.swing.JPanel {

    /**
     * Creates new form NoLoggedHeader
     */
    private MouseListener eventGetInfo;
    public boolean isLogin;
    private ActionListener eventChatBox;
    public LoggedHeader() {
        initComponents();
        setOpaque(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setColor(getBackground());
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gp = new GradientPaint(0, 0, Color.decode("#0052d4"), 0, getHeight(), Color.decode("#9cecfb"));
        g2.setPaint(gp);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        g2.fillRect(0, getHeight()-25, getWidth(), getHeight());

        super.paintComponent(grphcs);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHelp = new javax.swing.JButton();
        btnDiscount = new javax.swing.JButton();
        btnRoom = new javax.swing.JButton();
        user = new javax.swing.JPanel();
        avata = new uitravel.Components.RoundedImage();
        txtName = new javax.swing.JLabel();
        btnPartner = new javax.swing.JButton();

        btnHelp.setText("Hỗ trợ");
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHelpMousePressed(evt);
            }
        });
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnDiscount.setText("Khuyến mãi");
        btnDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiscountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiscountMouseExited(evt);
            }
        });
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });

        btnRoom.setText("Lịch sử");
        btnRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRoomMouseExited(evt);
            }
        });
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });

        user.setBackground(new java.awt.Color(102, 255, 255));
        user.setOpaque(false);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMousePressed(evt);
            }
        });

        avata.setOpaque(false);
        avata.setRadius(90);

        javax.swing.GroupLayout avataLayout = new javax.swing.GroupLayout(avata);
        avata.setLayout(avataLayout);
        avataLayout.setHorizontalGroup(
            avataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        avataLayout.setVerticalGroup(
            avataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Bao");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtName)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(txtName)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(avata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPartner.setText("Đăng ký đối tác");
        btnPartner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPartnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPartnerMouseExited(evt);
            }
        });
        btnPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(709, Short.MAX_VALUE)
                .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        // TODO add your handling code here:
            btnHelp.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
            btnHelp.setContentAreaFilled(true); // Fill content area to show background color
            btnHelp.setBorderPainted(false);
            btnHelp.repaint();
    }//GEN-LAST:event_btnHelpMouseEntered

    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
            btnHelp.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnHelpMouseExited

    private void btnDiscountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiscountMouseEntered
        btnDiscount.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnDiscount.setContentAreaFilled(true); // Fill content area to show background color
        btnDiscount.setBorderPainted(false);
        btnDiscount.repaint();
    }//GEN-LAST:event_btnDiscountMouseEntered

    private void btnDiscountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiscountMouseExited
        btnDiscount.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnDiscountMouseExited

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        
    }//GEN-LAST:event_btnDiscountActionPerformed

    private void btnRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseEntered
        btnRoom.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnRoom.setContentAreaFilled(true); // Fill content area to show background color
        btnRoom.setBorderPainted(false);
        btnRoom.repaint();
    }//GEN-LAST:event_btnRoomMouseEntered

    private void btnRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseExited
        btnRoom.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnRoomMouseExited

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered

        user.setOpaque(true);
        user.setBackground(new Color(0, 82, 212, 210));// TODO add your handling code here:
        user.repaint();
        user.revalidate();
    }//GEN-LAST:event_userMouseEntered

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        user.setOpaque(false);
        user.repaint();
        user.revalidate();

    }//GEN-LAST:event_userMouseExited

    private void userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMousePressed
       eventGetInfo.mousePressed(evt);
    }//GEN-LAST:event_userMousePressed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
       
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpMousePressed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        eventChatBox.actionPerformed(evt);      
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnPartnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartnerMouseEntered
        btnPartner.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnPartner.setContentAreaFilled(true); // Fill content area to show background color
        btnPartner.setBorderPainted(false);
        btnPartner.repaint();
    }//GEN-LAST:event_btnPartnerMouseEntered

    private void btnPartnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartnerMouseExited
        btnPartner.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnPartnerMouseExited

    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPartnerActionPerformed
      public void addChatEvent(ActionListener event){
        this.eventChatBox = event;
    }
    public void addEvent(MouseListener event) {
        this.eventGetInfo = event;
    }
    private void init() {
       btnHelp.setOpaque(false);
       btnHelp.setContentAreaFilled(false);
       btnHelp.setBorderPainted(false);
       btnHelp.setBorder(null); // Remove the border
       btnHelp.setForeground(Color.WHITE);
       
       btnDiscount.setOpaque(false);
       btnDiscount.setContentAreaFilled(false);
       btnDiscount.setBorderPainted(false);
       btnDiscount.setBorder(null); // Remove the border
       btnDiscount.setForeground(Color.WHITE);
       
       btnRoom.setOpaque(false);
       btnRoom.setContentAreaFilled(false);
       btnRoom.setBorderPainted(false);
       btnRoom.setBorder(null); // Remove the border
       btnRoom.setForeground(Color.WHITE);
       
       btnPartner.setOpaque(false);
       btnPartner.setContentAreaFilled(false);
       btnPartner.setBorderPainted(false);
       btnPartner.setBorder(null); // Remove the border
       btnPartner.setForeground(Color.WHITE);
        Font buttonFont = new Font("Times new roman", Font.BOLD, 16);
    
        btnDiscount.setFont(buttonFont);
        btnRoom.setFont(buttonFont);
        btnHelp.setFont(buttonFont);
        btnPartner.setFont(buttonFont);

        user.setOpaque(false);
      // myButton1.setContentAreaFilled(false);
      // myButton1.setBorderPainted(false);
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.Components.RoundedImage avata;
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnPartner;
    private javax.swing.JButton btnRoom;
    private javax.swing.JLabel txtName;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
