/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.Admin.TourInfo;

import uitravel.Components.TourInfo.Component.*;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class ADShortTourInfo extends javax.swing.JPanel {

    private ActionListener eventGetFullTourInfo;
    public void addEventGetTourInfo(ActionListener event) {
        this.eventGetFullTourInfo = event;
    }
    private String id;
    public ADShortTourInfo() {
        initComponents();
    }
    public void setTourID(String name){
        this.id = name;
        txtID.setText(name);
    }
    public String getTourID(){
        return id;
    }
    public void setTourName(String name){
        txtName.setText(name);
    }
    public void setPlace(String place){
        txtPlace.setText(place);
    }
   
     public void setScore(Double score){
        txtScore.setText(score.toString());
    }

     public void setPic(ImageIcon pictrue){
         pic.setbackgroundImage(pictrue);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new uitravel.Components.RoundedPanel();
        myButton1 = new uitravel.Components.MyButton();
        txtPlace = new javax.swing.JLabel();
        pic = new uitravel.Components.ImagePanel();
        txtScore = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtPlace1 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(302, 202));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setBorderColor(new java.awt.Color(204, 204, 204));
        roundedPanel1.setRadius(15);
        roundedPanel1.setWithBorder(true);

        myButton1.setBackground(new java.awt.Color(0, 0, 255));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Xem thông tin ");
        myButton1.setBorderColor(new java.awt.Color(0, 0, 255));
        myButton1.setColor(new java.awt.Color(0, 0, 255));
        myButton1.setColorClick(new java.awt.Color(0, 150, 255));
        myButton1.setColorOver(new java.awt.Color(0, 100, 255));
        myButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        txtPlace.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtPlace.setText("TP HCM");

        pic.setbackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/resources/BigBeach_GettyImages-874980426-ezgif.com-webp-to-png-converter.png"))); // NOI18N
        pic.setisTransparent(false);
        pic.setPreferredSize(new java.awt.Dimension(130, 142));
        pic.setRadius(15);
        pic.setwithBlack(true);

        txtScore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtScore.setForeground(new java.awt.Color(255, 255, 255));
        txtScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Star1.png"))); // NOI18N
        txtScore.setText("1");

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Du lịch Dĩ An");

        txtPlace1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        txtPlace1.setForeground(new java.awt.Color(255, 255, 255));
        txtPlace1.setText("ID:");

        txtID.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("TP HCM");

        pic.setLayer(txtScore, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pic.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pic.setLayer(txtPlace1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pic.setLayer(txtID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout picLayout = new javax.swing.GroupLayout(pic);
        pic.setLayout(picLayout);
        picLayout.setHorizontalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(picLayout.createSequentialGroup()
                        .addGroup(picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtScore)
                            .addGroup(picLayout.createSequentialGroup()
                                .addComponent(txtPlace1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID)))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        picLayout.setVerticalGroup(
            picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlace1)
                    .addComponent(txtID))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlace))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(roundedPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        roundedPanel1.setBorderColor(new Color(0,153,255));
        repaint();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
         roundedPanel1.setBorderColor(new Color(204,204,204));
                 repaint();

    }//GEN-LAST:event_formMouseExited

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        eventGetFullTourInfo.actionPerformed(evt);
    }//GEN-LAST:event_myButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.Components.MyButton myButton1;
    private uitravel.Components.ImagePanel pic;
    private uitravel.Components.RoundedPanel roundedPanel1;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPlace;
    private javax.swing.JLabel txtPlace1;
    private javax.swing.JLabel txtScore;
    // End of variables declaration//GEN-END:variables
}
