/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.Admin.TourInfo;

import uitravel.Admin.component.cell.TableActionCellRender;

/**
 *
 * @author ACER
 */
public class TourBookingData extends javax.swing.JPanel {

    /**
     * Creates new form TourBookingData
     */
    public TourBookingData() {
        initComponents();
        table.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bbg = new uitravel.Components.RoundedPanel();
        bg = new javax.swing.JLayeredPane();
        headerPic = new uitravel.Components.ImagePanel();
        txtName = new javax.swing.JTextArea();
        lblEdit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        roundedPanel1 = new uitravel.Components.RoundedPanel();
        lblAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        bbg.setBackground(new java.awt.Color(255, 255, 255));
        bbg.setBorderColor(new java.awt.Color(204, 204, 204));
        bbg.setPreferredSize(new java.awt.Dimension(1200, 700));
        bbg.setWithBorder(true);
        bbg.setLayout(new javax.swing.BoxLayout(bbg, javax.swing.BoxLayout.LINE_AXIS));

        bg.setPreferredSize(new java.awt.Dimension(1200, 700));

        headerPic.setbackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/resources/BigBeach_GettyImages-874980426-ezgif.com-webp-to-png-converter.png"))); // NOI18N
        headerPic.setisTransparent(false);
        headerPic.setRadius(30);
        headerPic.setwithBlack(true);

        txtName.setEditable(false);
        txtName.setColumns(20);
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setLineWrap(true);
        txtName.setRows(5);
        txtName.setText("Hoi An Basket Boat Tour Hoi An Basket Boat Tour Hoi An Basket Boat Tour Hoi An Basket Bo");
        txtName.setWrapStyleWord(true);
        txtName.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtName.setEnabled(false);
        txtName.setOpaque(false);
        txtName.setPreferredSize(new java.awt.Dimension(955, 179));

        lblEdit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Compose.png"))); // NOI18N
        lblEdit.setText("Chỉnh sửa");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        txtID.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("21521857");

        headerPic.setLayer(txtName, javax.swing.JLayeredPane.PALETTE_LAYER);
        headerPic.setLayer(lblEdit, javax.swing.JLayeredPane.PALETTE_LAYER);
        headerPic.setLayer(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);
        headerPic.setLayer(txtID, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout headerPicLayout = new javax.swing.GroupLayout(headerPic);
        headerPic.setLayout(headerPicLayout);
        headerPicLayout.setHorizontalGroup(
            headerPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPicLayout.createSequentialGroup()
                .addGroup(headerPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(headerPicLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPicLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEdit)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        headerPicLayout.setVerticalGroup(
            headerPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPicLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(headerPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID)
                    .addComponent(lblEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        lblBack.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        lblBack.setForeground(new java.awt.Color(204, 255, 255));
        lblBack.setText("Quay lại trang chủ");

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblAdd.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(0, 204, 0));
        lblAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add.png"))); // NOI18N
        lblAdd.setText("Thêm chuyến đi");

        table.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ngày đi", "Số lượng khách", "Doanh thu", "Tình trạng", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdd))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAdd)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        bg.setLayer(headerPic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bg.setLayer(lblBack, javax.swing.JLayeredPane.PALETTE_LAYER);
        bg.setLayer(roundedPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1013, Short.MAX_VALUE)))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(headerPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(lblBack)
                    .addContainerGap(640, Short.MAX_VALUE)))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(237, Short.MAX_VALUE)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        bbg.add(bg);

        add(bbg);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.Components.RoundedPanel bbg;
    private javax.swing.JLayeredPane bg;
    private uitravel.Components.ImagePanel headerPic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEdit;
    private uitravel.Components.RoundedPanel roundedPanel1;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextArea txtName;
    // End of variables declaration//GEN-END:variables
}
