/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uitravel;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.raven.datechooser.DateChooser;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import net.miginfocom.swing.MigLayout;
import raven.datetime.component.date.DatePicker;
import uitravel.Components.MainUI.Header;
import uitravel.Components.MainUI.Hotel;
import uitravel.Components.MyButton;
import uitravel.Components.MyTextField;
import uitravel.Components.RoundedPanel;

/**
 *
 * @author ACER
 */
public class UserMain extends javax.swing.JFrame {

    /**
     * Creates new form UserMain
     */

    private MigLayout layout;
    private Header header;
    public UserMain() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setBorder(null);
        main.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        main.setAutoscrolls(true);
        main.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane main;
    // End of variables declaration//GEN-END:variables
    private MyTextField txtSearch;
    private MyTextField txtDate;
    private MyTextField txtRoom;
    private MyButton btnSearch;
    private DateChooser selectDate;
    private javax.swing.JLayeredPane bg;
    private RoundedPanel pnlHotel;

    private void init() {
        
        bg = new JLayeredPane();
        //bg.setPreferredSize(new java.awt.Dimension(1400, 10000));

        layout = new MigLayout("wrap, fill, insets 0","[]", "12[]12[]12");
        bg.setLayout(layout);
        header = new Header();
        bg.add(header,"dock north, width 100%,height 250");
        header.addEvent((ActionEvent e)->{
            LoginMain lm = new LoginMain();
            lm.setLogin(header.isLogin);
            lm.setVisible(true);
            dispose();
        });
        txtSearch = new uitravel.Components.MyTextField();
        txtSearch.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Pin - 1.png"))); // NOI18N
        txtSearch.setOpaque(false);
        txtSearch.setText("Nhập tên khách sạn, địa điểm");
        txtSearch.addFocusListener(new FocusAdapter(){
              @Override
              public void focusGained(FocusEvent e) {
                  if("Nhập tên khách sạn, địa điểm".equals(txtSearch.getText())){
                      txtSearch.setText("");
                  }
              }
              @Override
               public void focusLost(FocusEvent e) {
                   if("".equals(txtSearch.getText())){
                       txtSearch.setText("Nhập tên khách sạn, địa điểm");
                   }
               }
        });
        txtDate = new MyTextField();
        txtDate.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Calendar.png"))); // NOI18N

        txtDate.setOpaque(false);
        txtRoom = new MyTextField();
        txtRoom.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/House.png"))); // NOI18N
        txtRoom.setOpaque(false);

        Icon icon = new ImageIcon(getClass().getResource("/resources/Loupe.PNG"));
        btnSearch = new MyButton();
        btnSearch.setIcon(icon);
        btnSearch.setText("");
        //btnSearch.setBackground(new Color(255,128,0));
        btnSearch.setColor(new Color(255,128,0));
        btnSearch.setColorOver(new Color(255,153,0));
        bg.add(txtSearch,"cell 0 0, width 28%,height 50, align left,aligny top,gapleft 10%,gapright 0");
        bg.add(txtDate,"cell 0 0,width 25%,height 50, align right,aligny top,gapleft 0, gapright 0");
        bg.add(txtRoom,"cell 0 0,width 25%,height 50, align right,aligny top,gapleft0");
        bg.add(btnSearch,"cell 0 0, align right,height 50,aligny top,gapleft0,gapright 0%");
        selectDate = new DateChooser();
        selectDate.setTextField(txtDate);
        selectDate.setBetweenCharacter(" đến ");
        selectDate.setDateSelectionMode(DateChooser.DateSelectionMode.BETWEEN_DATE_SELECTED);
       
        //Hotel t = new Hotel();
        //bg.add(t);
        pnlHotel = new RoundedPanel();
        pnlHotel.setPreferredSize(new Dimension(1400,1000));
        pnlHotel.setBackground(Color.WHITE);
        pnlHotel.setRadius(30);
        pnlHotel.setOpaque(false);
        
        Hotel t = new Hotel();
        t.setPreferredSize(new Dimension(300,350));
        pnlHotel.setLayout(new MigLayout("fill, insets 0","push[]push","[]push"));
        pnlHotel.add(t);
        bg.add(pnlHotel);

        main.setViewportView(bg);

        //jScrollPane1.getViewport().add(bg);
    }
    

   
}
