/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.User.MainUI;

import java.awt.*;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.RenderingHints;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;

/**
 *
 * @author ACER
 */
public class NoLoggedHeader extends javax.swing.JPanel {

    /**
     * Creates new form NoLoggedHeader
     */
    private ActionListener eventLogin;
    private ActionListener eventChatBox;
    private ActionListener eventAdmin;

    public boolean isLogin;
    public NoLoggedHeader() {
        initComponents();
        setOpaque(false);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton1 = new uitravel.Components.MyButton();
        myButton2 = new uitravel.Components.MyButton();
        btnHelp = new javax.swing.JButton();
        btnDiscount = new javax.swing.JButton();
        btnRoom = new javax.swing.JButton();
        btnPartner = new javax.swing.JButton();
        customLineComponent1 = new uitravel.Components.CustomLineComponent();
        customLineComponent2 = new uitravel.Components.CustomLineComponent();

        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Đăng ký");
        myButton1.setToolTipText("");
        myButton1.setBorderColor(new java.awt.Color(255, 255, 255));
        myButton1.setColor(new java.awt.Color(0, 102, 255));
        myButton1.setColorClick(new java.awt.Color(51, 153, 255));
        myButton1.setColorOver(new java.awt.Color(0, 102, 204));
        myButton1.setContentAreaFilled(true);
        myButton1.setOpaque(false);
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Đăng nhập");
        myButton2.setBorderColor(new java.awt.Color(255, 255, 255));
        myButton2.setColor(new java.awt.Color(0, 102, 255));
        myButton2.setColorClick(new java.awt.Color(51, 153, 255));
        myButton2.setColorOver(new java.awt.Color(0, 102, 204));
        myButton2.setContentAreaFilled(true);
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        btnHelp.setText("Hỗ trợ");
        btnHelp.setFocusPainted(false);
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHelpMouseExited(evt);
            }
        });
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnDiscount.setText("Khuyến mãi");
        btnDiscount.setFocusPainted(false);
        btnDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDiscountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDiscountMouseExited(evt);
            }
        });
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });

        btnRoom.setText("Lịch sử");
        btnRoom.setFocusPainted(false);
        btnRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRoomMouseExited(evt);
            }
        });

        btnPartner.setText("Trang quản trị");
        btnPartner.setFocusPainted(false);
        btnPartner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPartnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPartnerMouseExited(evt);
            }
        });
        btnPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnerActionPerformed(evt);
            }
        });

        customLineComponent1.setLineColor(new java.awt.Color(0, 51, 102));

        customLineComponent2.setLineColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addComponent(customLineComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(customLineComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(customLineComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(customLineComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        this.isLogin = false;
        eventLogin.actionPerformed(evt);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        this.isLogin = true;
        eventLogin.actionPerformed(evt);
    }//GEN-LAST:event_myButton2ActionPerformed

    private void btnHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseEntered
        // TODO add your handling code here:
            btnHelp.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
            btnHelp.setContentAreaFilled(true); // Fill content area to show background color
            btnHelp.setBorderPainted(false);
            btnHelp.repaint();
    }//GEN-LAST:event_btnHelpMouseEntered

    private void btnHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHelpMouseExited
            btnHelp.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnHelpMouseExited

    private void btnDiscountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiscountMouseEntered
        btnDiscount.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnDiscount.setContentAreaFilled(true); // Fill content area to show background color
        btnDiscount.setBorderPainted(false);
        btnDiscount.repaint();
    }//GEN-LAST:event_btnDiscountMouseEntered

    private void btnDiscountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiscountMouseExited
        btnDiscount.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnDiscountMouseExited

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        
    }//GEN-LAST:event_btnDiscountActionPerformed

    private void btnRoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseEntered
        btnRoom.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnRoom.setContentAreaFilled(true); // Fill content area to show background color
        btnRoom.setBorderPainted(false);
        btnRoom.repaint();
    }//GEN-LAST:event_btnRoomMouseEntered

    private void btnRoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoomMouseExited
        btnRoom.setContentAreaFilled(false); // Fill content area to show background color

    }//GEN-LAST:event_btnRoomMouseExited

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
       eventChatBox.actionPerformed(evt);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnPartnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartnerMouseEntered
        btnPartner.setBackground(new Color(0, 82, 212, 210)); // semi-transparent white
        btnPartner.setContentAreaFilled(true); // Fill content area to show background color
        btnPartner.setBorderPainted(false);
        btnPartner.repaint();
    }//GEN-LAST:event_btnPartnerMouseEntered

    private void btnPartnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartnerMouseExited
        btnPartner.setContentAreaFilled(false); // Fill content area to show background color
    }//GEN-LAST:event_btnPartnerMouseExited
    
    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        eventAdmin.actionPerformed(evt);
    }//GEN-LAST:event_btnPartnerActionPerformed
    public void addAminUIEvent(ActionListener event){
        this.eventAdmin = event;
    }
    public void addChatEvent(ActionListener event){
        this.eventChatBox = event;
    }
    public void addEvent(ActionListener event) {
        this.eventLogin = event;
    }
    private void init() {
       btnHelp.setOpaque(false);
       btnHelp.setContentAreaFilled(false);
       btnHelp.setBorderPainted(false);
       btnHelp.setBorder(null); // Remove the border
       btnHelp.setForeground(Color.WHITE);
       
       btnDiscount.setOpaque(false);
       btnDiscount.setContentAreaFilled(false);
       btnDiscount.setBorderPainted(false);
       btnDiscount.setBorder(null); // Remove the border
       btnDiscount.setForeground(Color.WHITE);
       
       btnRoom.setOpaque(false);
       btnRoom.setContentAreaFilled(false);
       btnRoom.setBorderPainted(false);
       btnRoom.setBorder(null); // Remove the border
       btnRoom.setForeground(Color.WHITE);
       
        myButton1.setTransparent(false);
        myButton1.setForeground(Color.WHITE);
        myButton2.setTransparent(false);
        myButton2.setForeground(Color.WHITE);
        
        btnPartner.setOpaque(false);
        btnPartner.setContentAreaFilled(false);
        btnPartner.setBorderPainted(false);
        btnPartner.setBorder(null); // Remove the border
        btnPartner.setForeground(Color.WHITE);
        
        Font buttonFont = new Font("Times new roman", Font.BOLD, 16);
        myButton1.setFont(buttonFont);
        myButton2.setFont(buttonFont);
        btnDiscount.setFont(buttonFont);
        btnRoom.setFont(buttonFont);
        btnHelp.setFont(buttonFont);
        btnPartner.setFont(buttonFont);

      // myButton1.setContentAreaFilled(false);
      // myButton1.setBorderPainted(false);
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnPartner;
    private javax.swing.JButton btnRoom;
    private uitravel.Components.CustomLineComponent customLineComponent1;
    private uitravel.Components.CustomLineComponent customLineComponent2;
    private uitravel.Components.MyButton myButton1;
    private uitravel.Components.MyButton myButton2;
    // End of variables declaration//GEN-END:variables
}
