/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.User.MainUI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class Place extends javax.swing.JPanel {
    private MouseListener event;
    private String id;
    public Place() {
        initComponents();
        init();
    }
    public void setID(String id){
        this.id = id;
    }
    public String getID(){
        return id;
    }
    public void init(){
       
    }
    public void setBackGroundIMG(ImageIcon img){
        background.setbackgroundImage(img);
    }
    public void setTxtPlace(String txt){
        txtPlace.setText(txt);
    }    
    public String getTxtPlace() {
        return txtPlace.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        background = new uitravel.Components.ImagePanel();
        txtPlace = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(350, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setbackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/resources/backimg.jpg"))); // NOI18N
        background.setisTransparent(false);
        background.setRadius(20);
        background.setwithBlack(true);
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        txtPlace.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPlace.setForeground(new java.awt.Color(255, 255, 255));
        txtPlace.setText("TP.HCM");

        jLayeredPane1.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPlace, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(txtPlace)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(txtPlace)
                    .addGap(40, 40, 40)))
        );

        add(jLayeredPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
            event.mousePressed(evt);
    }//GEN-LAST:event_backgroundMousePressed


    public void getPlaceTour(MouseAdapter mouseAdapter) {
        this.event = mouseAdapter;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.Components.ImagePanel background;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel txtPlace;
    // End of variables declaration//GEN-END:variables



}
