/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.User.MainUI.Chat;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author ACER
 */
public class ChatItem extends javax.swing.JPanel {

    /**
     * Creates new form ChatItem
     */
    public ChatItem() {
        initComponents();
        txt.setEditable(false);
        txt.setOpaque(false);
        txt.setBackground(new Color(0, 0, 0, 0));

    }
    public void setText(String text) {
            txt.setText(text);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new uitravel.User.MainUI.Chat.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(txt);
    }// </editor-fold>//GEN-END:initComponents
    @Override
       protected void paintComponent(Graphics grphcs) {
           Graphics2D g2 = (Graphics2D) grphcs;
           g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
           g2.setColor(getBackground());
           g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
           super.paintComponent(grphcs);
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.User.MainUI.Chat.JIMSendTextPane txt;
    // End of variables declaration//GEN-END:variables
}
