/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.User.MainUI.Chat;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author ACER
 */
public class CmtItem extends javax.swing.JPanel {

    /**
     * Creates new form ChatItem
     */
    public CmtItem() {
        initComponents();
        txt.setEditable(false);
        txt.setEnabled(false);
        txt.setOpaque(false);
        txt.setBackground(new Color(0, 0, 0, 0));
        txt.setFont(new Font("Times New Roman", 0, 14));
    }

    public void setAttitude(String txt){
        JLabel t = new JLabel(txt);
        t.setFont(new Font("Times New Roman", 2, 12));
        switch (txt) {
            case "Tích cực" -> {
                t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thumb_up.png"))); // NOI18N
                t.setForeground(new Color(4,161,48));
            }
            case "Tiêu cực" -> {
                t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thumb_down.png"))); // NOI18N
                t.setForeground(new Color(255,0,0));
            }
            default -> {
                return;
            }
        }
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.RIGHT,0,0));
        layer.setBorder(new EmptyBorder(0,5,10,5));
        layer.add(t);
        add(layer,0);
    }
    public void setUserName(String txt){
        JLabel t = new JLabel(txt);
        t.setFont(new Font("Times New Roman", 1, 16));
        JLayeredPane layer = new JLayeredPane();
        layer.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));
        layer.setBorder(new EmptyBorder(10,5,0,5));
        layer.add(t);
        add(layer,0);
    }
    public void setText(String text) {
            txt.setText(text);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new uitravel.User.MainUI.Chat.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt.setOpaque(false);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents
    @Override
       protected void paintComponent(Graphics grphcs) {
           Graphics2D g2 = (Graphics2D) grphcs;
           g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
           g2.setColor(getBackground());
           g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
           super.paintComponent(grphcs);
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uitravel.User.MainUI.Chat.JIMSendTextPane txt;
    // End of variables declaration//GEN-END:variables
}
