/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uitravel.Components;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class RoundedImage extends javax.swing.JPanel {
    private Image image;
    private int radius;

    /**
     * Creates new form RoundedImage
     */
    public RoundedImage() {
        initComponents();
        setImage("/resources/backimg.jpg");

    }
    @Override
       protected void paintComponent(Graphics g) {
           super.paintComponent(g);
           if (image != null) {
               //setOpaque(false);
               java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
               g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

               // Create a rounded rectangle shape for clipping
               RoundRectangle2D roundedRectangle = new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), radius, radius);
               g2.setClip(roundedRectangle);

               // Draw the image
               g2.drawImage(image, 0, 0, getWidth(), getHeight(), this);

               g2.dispose();
           }
       }

    public void setImage(String imagePath) {
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        image= icon.getImage();
        repaint();
    }
    public Image getImage(){
        return image;
    }
    public void setRadius(int radius){
        this.radius = radius;
    }
    public int getRadius(){
        return radius;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
